name: 🔖 Release

description: Release applications

inputs:
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - run: git tag
      shell: bash

    - name: Version
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: npx nx affected --base=$(git describe --abbrev=0 --tags) --target=version --trackDeps --with-deps --allow-empty-release --parallel=1 --verbose

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        tags: true
