name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  preinstall:
    name: Cache install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install packages
        run: npm ci --verbose

  test:
    needs: preinstall
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v4

      - name: Install packages
        run: npm ci --verbose

      - name: Check code formatting by using prettier config
        if: github.event_name == 'push'
        run: npx nx format:check --all

      - name: Check code formatting by using prettier config
        if: github.event_name == 'pull_request'
        run: npx nx format:check

      - name: Lint
        if: github.event_name == 'push'
        run: npx nx run-many --target=lint --all

      - name: Lint
        if: github.event_name == 'pull_request'
        run: npx nx affected --target=lint

      - name: Test
        if: github.event_name == 'push'
        run: npx nx run-many --target=test --ci --runInBand --all

      - name: Test
        if: github.event_name == 'pull_request'
        run: npx nx affected --target=test --ci --runInBand

  build:
    needs: preinstall
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v4

      - name: Install packages
        run: npm ci --verbose

      - name: Build
        if: github.event_name == 'push'
        run: npx nx run-many --target=build --all

      - name: Build
        if: github.event_name == 'pull_request'
        run: npx nx affected --target=build
