name: Push

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Prepare
  #       uses: ./github/actions/prepare
  #       with:
  #         git_bot_token: ${{ secrets.GIT_BOT_TOKEN }}

  release:
    runs-on: ubuntu-latest

    # needs: [test]

    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          git_bot_token: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GIT_BOT_TOKEN }}
