name: Push

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/create-github-app-token@v1
  #       id: app-token
  #       with:
  #         app-id: ${{ vars.GH_APP_ID }}
  #         private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  #     - name: Prepare
  #       uses: ./.github/actions/prepare
  #       with:
  #         cache_node_modules_key: node-modules-${{ hashFiles('package-lock.json') }}
  #         git_bot_token: ${{ steps.app-token.outputs.token }}

  release:
    runs-on: ubuntu-latest

    # needs: [test]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          cache_node_modules_key: node-modules-${{ hashFiles('package-lock.json') }}
          git_bot_token: ${{ steps.app-token.outputs.token }}

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ steps.app-token.outputs.token }}
